# Generated by Django 4.1.5 on 2023-01-12 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=32, null=True, verbose_name='Name')),
                ('description', models.CharField(blank=True, max_length=128, null=True, verbose_name='Description')),
                ('serial', models.PositiveIntegerField(blank=True, null=True, verbose_name='Serial Number')),
            ],
            options={
                'db_table': 'device',
            },
        ),
    ]
