# Generated by Django 4.1.5 on 2023-02-01 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0003_alter_device_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='name',
            new_name='device',
        ),
        migrations.AddField(
            model_name='device',
            name='brand',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Brand'),
        ),
        migrations.AddField(
            model_name='device',
            name='model',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Model'),
        ),
    ]
