# Generated by Django 4.1.5 on 2023-02-01 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0005_device_date_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='failure',
            field=models.CharField(default='', max_length=64, verbose_name='Failure'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='device',
            name='device',
            field=models.CharField(default='none', max_length=32, verbose_name='Name'),
            preserve_default=False,
        ),
    ]
