# Generated by Django 4.1.5 on 2023-02-01 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0006_device_failure_alter_device_device'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='failure',
        ),
    ]
