# Generated by Django 4.1.5 on 2023-02-01 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0008_rename_device_device_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Note',
        ),
    ]
