# Generated by Django 4.1.5 on 2023-05-23 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0010_rename_user_device_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='description',
        ),
    ]
