# Generated by Django 4.1.5 on 2023-02-01 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='assignment',
            table='assignment',
        ),
    ]
