# Generated by Django 4.1.5 on 2023-02-02 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_delete_note'),
        ('workshop', '0004_alter_consideration_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, max_length=512, null=True, verbose_name='Note')),
                ('invoice', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workshop.invoice')),
                ('repair_order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.repairorder')),
            ],
            options={
                'db_table': 'note',
            },
        ),
        migrations.DeleteModel(
            name='Consideration',
        ),
    ]
