# Generated by Django 4.1.5 on 2023-05-15 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0006_assignment_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='is_active',
        ),
    ]
