# Generated by Django 4.1.5 on 2023-05-21 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonenumber',
            name='is_whatsapp_number',
            field=models.BooleanField(default=True, verbose_name='Is Whatsapp Number'),
        ),
    ]
