# Generated by Django 4.1.5 on 2025-08-26 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_phonenumber_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dni',
            field=models.PositiveIntegerField(null=True, verbose_name='Identification Document'),
        ),
    ]
