# Generated by Django 4.1.5 on 2023-01-12 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Failture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=32, verbose_name='Description of fault')),
            ],
            options={
                'db_table': 'failture',
            },
        ),
        migrations.CreateModel(
            name='RepairOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(max_length=256, verbose_name='Failture')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.device')),
                ('failture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.failture')),
            ],
            options={
                'db_table': 'repair_order',
            },
        ),
    ]
