# Generated by Django 4.1.5 on 2023-02-01 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_remove_repairorder_failture_repairorder_failture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='note',
            field=models.TextField(blank=True, max_length=512, null=True, verbose_name='Note'),
        ),
    ]
