# Generated by Django 4.1.5 on 2023-02-02 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_alter_note_note'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Note',
        ),
    ]
